### ISSUE TITLE
OrderBy a field in expanded element does not work as expected

### ISSUE THREAD

**Issue by ErJer** [object/Simple.OData.Client#224]
This:

```
var settings = new ODataClientSettings();
settings.BaseUri = new Uri("http://services.odata.org/V4/Northwind/Northwind.svc/");

var client = new ODataClient(settings);

var result = await client.For<Product>()
	.Expand(p=>p.Category)
	.Select(p => new { p.ProductName, p.Category.CategoryName})
	.OrderBy(p=>p.Category.CategoryName)
	.FindEntriesAsync();

var list = result.ToList();

```

Produces following query:
http://services.odata.org/V4/Northwind/Northwind.svc/Products?$expand=Category($select=CategoryName;$orderby=CategoryName)&$select=ProductName

The resulting list is not ordered by CategoryName. Expected would be the outcome of this query:
http://services.odata.org/V4/Northwind/Northwind.svc/Products?$expand=Category($select=CategoryName)&$select=ProductName&$orderby=Category/CategoryName

**Comment by object** [comment]
Thank you for the issue report. I believed it's fixed now, you can test the version 4.18 that I just uploaded to NuGet.

**Comment by adistef** [comment]
This is not fixed for the initial scenario. However it works when the navigation property(ies) involved in the order by are not contained by the expand clause.

Working:
`var result = await client.For<Product>()
    .Expand(p=>p.Supplier)
    .OrderBy(p=>p.Category.CategoryName)
    .FindEntriesAsync();
var list = result.ToList();`

Not working:
`var result = await client.For<Product>()
    .Expand(p=>p.Category)
    .OrderBy(p=>p.Category.CategoryName)
    .FindEntriesAsync();
var list = result.ToList();`

**Comment by ErJer** [comment]
Thanks for the answer.

Since this is not yet fixed, do I have to add the same issue again?

**Comment by object** [comment]
I am reopening the issue and will investigate it.

**Comment by object** [comment]
Fixed in 4.20.
