### ISSUE TITLE
Retrieve Edm.Date using typed syntax?

### ISSUE THREAD

**Issue by jameshawkins** [object/Simple.OData.Client#243]
Hello. Is it possible to retrieve and serialize and Odata v4 value of type Edm.Date using the typed syntax? I'm getting the following error when I try:

Object of type 'Microsoft.OData.Edm.Library.Date' cannot be converted to type 'System.Nullable`1[System.DateTime]'.

Here's my query:

await client
    .For<Opportunity>()
    .Key(opportunityId)
    .Expand(o => o.ParentContact)
        .FindEntryAsync();

My ParentContect type has a nullable DateTime property that causes the error.  I've tried using DateTimeOffset and string but both result in the same type of error.  There doesn't seem to be an appropriate C# type for this.  Thanks.

**Comment by object** [comment]
Hi, there are some improvements in date/time handling in the version 4.20 that I just released. Can you try that and let me know if it solves your issue?

**Comment by jameshawkins** [comment]
Hi, sorry for the extremely long delay... I finally got around to trying the latest client version (4.21) and the issue is still present.  I'm currently working around this issue by using the untyped syntax for the query and then deserializing the result myself using the json.net library from Newtonsoft.

**Comment by object** [comment]
@NetTecture can you send the following:
1. Service metadata document
2. Sample code that triggers the error (with entity type definition)
3. Response payload (from Fiddler or similar tool)
You send this to vagif.abilov at gmail.

**Comment by NetTecture** [comment]
@object Big presentation tomorrow. Give me till the day after to put that together ;) You get it.

**Comment by b0raG** [comment]
Hello.
Do we have any update to solve this issue?

**Comment by object** [comment]
@b0raG I am still waiting for the information I requested (see above).

**Comment by NetTecture** [comment]
Ok, here we go. It is really trivial.

* Make a property of type DateTime. WORKS.

https://localhost:44361/Account?$top=10

Metadata:

<Property Name="Created" Type="Edm.DateTimeOffset" Nullable="false"/>

Data:

,"Created":"2018-01-15T08:50:20.68Z"}

* Slap an Edm.Time attribute on it:

[Column(TypeName = "date")]

Metadata changes:

<Property Name="Created" Type="Edm.Date" Nullable="false"/>

And data changes:

"Created":"2017-12-18"

Simple as it gets. And the mentioned error happens.

Note that there are actually structs for this and time of day that are optional.  Which we are not using ATM, so this bug is really about the whole issue just by getting a date.

Documentation for this:

http://odata.github.io/WebApi/12-01-DateAndTimeOfDayWithEF/

**Comment by object** [comment]
@b0raG @jameshawkins @NetTecture I just pushed version 5.5.0-beta1 that is supposed to fix this issue.

**Comment by kedrzu** [comment]
In version 5.10 it still does not work.

**Comment by mcattle** [comment]
PR #828 fixes this issue.
