### ISSUE TITLE
Try to use Simple.OData.Client in a .Net Core 2.x App

### ISSUE THREAD

**Issue by jesuspsalas** [object/Simple.OData.Client#468]
Hi, I'm trying to use your library on .Net Core 2.x App to access a OData V2 endpoint, however no matter what I do I keep getting a 

Could not load file or assembly 'System.Net.Http.Extensions, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

Is .Net Core 2.x supported? 
Thanks!

**Comment by petteas** [comment]
I have the same problem and question. Also with the new 5.0.0 stable version i get the same error as you @jesuspsalas. Here with callstack when i call FindEntriesAsync():  
```System.AggregateException: One or more errors occurred. (Could not load file or assembly 'System.Net.Http.Extensions, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.) ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http.Extensions, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
   at Simple.OData.Client.HttpConnection.CreateMessageHandler(ODataClientSettings settings)
   at Simple.OData.Client.HttpConnection..ctor(ODataClientSettings settings)
   at Simple.OData.Client.Session.GetHttpConnection()
   at Simple.OData.Client.RequestRunner.<ExecuteRequestAsync>d__2.MoveNext()```

**Comment by object** [comment]
Well, it should be since the library supports .NET Standard 2.0. I actually built and tested it on Mac. On what platform are you running it?

**Comment by object** [comment]
Yes, I confirm a problem, looking into it...

**Comment by object** [comment]
@petteas @jesuspsalas I believe it was a problem with the content of the NuGet package (basically it included wrong files). I just pushed 5.0.0.1 package. Can you give it a try?

**Comment by jesuspsalas** [comment]
Thanks @object I'll give a try, I believe I still have the test code in my project...

**Comment by petteas** [comment]
Thanks @object. Now this issue is resolved, however it lead to another issue for me, the exact same as @kyleherzog  describes in #467

**Comment by object** [comment]
I believe this one is fixed now. Try version 5.1.0.

**Comment by petteas** [comment]
Thank you so much @object. It works for me now

**Comment by object** [comment]
Good to know!
